apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tools
spec:
  containers:
    - name: tools
      image: docker:latest
      command:
        - cat
      tty: true
      volumeMounts:
      - mountPath: '/var/run/docker.sock'
        name: docker-sock
      - mountPath: "/var/certs"
        name: "volume-0"
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - configMap:
        name: "ca-bundle"
        optional: false
      name: "volume-0"
